/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#414754",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        outline: "#727785",
        "outline-variant": "#c1c6d6",
        "surface-tint": "#005bc0",
        primary: "#005bbf",
        "on-primary": "#ffffff",
        "primary-container": "#1a73e8",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#adc7ff",
        secondary: "#006e2c",
        "on-secondary": "#ffffff",
        "secondary-container": "#86f898",
        "on-secondary-container": "#00722f",
        tertiary: "#795900",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#987000",
        "on-tertiary-container": "#ffffff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc7ff",
        "on-primary-fixed": "#001a41",
        "on-primary-fixed-variant": "#004493",
        "secondary-fixed": "#89fa9b",
        "secondary-fixed-dim": "#6ddd81",
        "on-secondary-fixed": "#002108",
        "on-secondary-fixed-variant": "#005320",
        "tertiary-fixed": "#ffdfa0",
        "tertiary-fixed-dim": "#fbbc05",
        "on-tertiary-fixed": "#261a00",
        "on-tertiary-fixed-variant": "#5c4300",
        background: "#f8f9fa",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
      },
      borderRadius: {
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        "container-padding": "20px",
        gutter: "16px",
        "section-gap": "32px",
        safe: "env(safe-area-inset-bottom)",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "headline-lg": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "headline-lg-mobile": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "title-md": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "body-rg": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "label-lt": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "display-stat": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-rg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lt": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "300" }],
        "display-stat": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
      boxShadow: {
        glass: "0px 4px 24px rgba(0, 0, 0, 0.04)",
        "glass-up": "0px -4px 24px rgba(0, 0, 0, 0.04)",
        primary: "0px 4px 12px rgba(26, 115, 232, 0.3)",
      },
    },
  },
  plugins: [],
};
